### ISSUE TITLE
dosent work on deck due to updated libc, and or pyinstaller being complied on a higher version of libc on a arch based distro

### ISSUE THREAD

**Issue by Epic62790** [BrownNPC/pg3d-injector-linux#1]
ldd (GNU libc) 2.37
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
Written by Roland McGrath and Ulrich Drepper.

theres is a patch for it on a thread. that used a python 3.9 version with ubuntu that made the injector work

**Comment by Epic62790** [comment]
[43599] Error loading Python lib '/tmp/_MEIu8gOUi/libpython3.12.so.1.0': dlopen: /usr/lib/libm.so.6: version `GLIBC_2.38' not found (required by /tmp/_MEIu8gOUi/libpython3.12.so.1.0)

**Comment by BrownNPC** [comment]
This is fixed on the latest release.
