### ISSUE TITLE
add steam deck beta/preview updates build version of injector

### ISSUE THREAD

**Issue by Epic62790** [BrownNPC/pg3d-injector-linux#3]
when i switched to a newer build of steamos which is the preview of 3.6, which recently got an update i just want to say the injector for the deck does not work on this version and that i have a other version that is fixed and i want this to be fixed for users on the non stable, like beta/preview builds of the steam deck

**Comment by BrownNPC** [comment]
fixed, there is a steamos 36 build in release 2
